# -*- coding: utf-8 -*-
"""isniklucky

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SD8_uuOmfqnWOwNvChBoOcDc-Qp-nLyO
"""

!pip install streamlit
import streamlit as st
import random

# Page setup
st.set_page_config(page_title="Niklas's Luck", page_icon="🍀", layout="centered")

# Title and description
st.title("Does Nik get some today? 🤪")
st.markdown("Are you lucky or not 😇")

# Button to generate the answer
if st.button("Ask Noks"):
    # Randomly choose between "Yes" and "No"
    answer = random.choice(["Yes, baby 🥰", "Womp Womp"])

    # Display the answer
    if answer == "Yes, baby 🥰":
        st.balloons()
        st.success(f"Noks says: **{answer}!** 🎉")
    else:
        st.error(f"Noks says: **{answer}.** 😢")

# Footer note
st.info("Disclaimer: This is binding between Nik and Noks")

# Write the streamlit app to a file
streamlit_code = """
import streamlit as st
import random

st.set_page_config(page_title="Niklas's Luck", page_icon="🍀", layout="centered")

st.title("Does Nik get some today? 🤪")
st.markdown("Are you lucky or not 😇!")

if st.button("Ask Noks"):
    answer = random.choice(["Yes, baby 🥰", "Womp Womp"])

    if answer == "Yes, baby 🥰":
        st.balloons()
        st.success(f"The Oracle says: **{answer}!** 🎉")
    else:
        st.error(f"The Oracle says: **{answer}.** 😢")

st.info("Disclaimer: TThis is binding between Nik and Noks")
"""

with open("isniklucky.py", "w") as f:
    f.write(streamlit_code)

# You can run this app locally using:
# !streamlit run niklas_luck_app.py

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# streamlit

!streamlit run isniklucky.py